##DE_MART CASE STUDY

USE CASE1;
select * from weekly_sales limit 10;


##DATA CLEANSING--EXTRACTED DAY,MONTH,YEAR FROM DATE--REPLACED NULL VALUES TO UNKNOWN IN SEGMENT
##EXTRACTED AGE_BAND AND DEMOGRAPHIC FROM SEGMENT FOR EG: C3 -- C REFERS TO COUPLES AND 3 REFERS TO RETRIES


CREATE TABLE CLEAN_WEEKLY_SALES AS 
SELECT WEEK_DATE,WEEK(WEEK_DATE) AS WEEK_NUMBER,
MONTH(WEEK_DATE) AS MONTH_NUMBER,
YEAR(WEEK_DATE) AS YEAR_NUMBER,
REGION,PLATFORM,
CASE WHEN SEGMENT = NULL THEN 'UNKNOWN'
ELSE SEGMENT 
END AS SEGMENT,
CASE WHEN RIGHT(SEGMENT,1)='1' THEN 'YOUNG ADULT'
WHEN RIGHT(SEGMENT,1)='2' THEN 'MIDDLE AGED'
WHEN RIGHT(SEGMENT,1) IN ('3','4') THEN 'RETRIES'
ELSE 'UNKNOWN'
END AS AGE_BAND,
CASE WHEN LEFT(SEGMENT,1) = 'C' THEN 'COUPLES'
WHEN LEFT(SEGMENT,1) = 'F' THEN 'FAMILIES'
ELSE 'UNKNOWN'
END AS DEMOGRAPHIC,
CUSTOMER_TYPE,TRANSACTIONS,SALES,
ROUND(SALES/TRANSACTIONS,2) AS AVG_TRANSACTIONS
FROM WEEKLY_SALES;

SELECT * FROM CLEAN_WEEKLY_SALES LIMIT 10;

## DATA EXPLORATION
##RETRIVE WEEK_NUMBERS THAT ARE NOT PRESENT IN THE DATA SET
##CREATED A TABLE WITH 52 AUTO_INCREMENTED ID'S 
DROP TABLE SEQ100;
CREATE TABLE SEQ100(X INT auto_increment primary KEY);
INSERT INTO SEQ100 VALUES(),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100 VALUES(),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100 VALUES(),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100 VALUES(),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100 VALUES(),(),(),(),(),(),(),(),(),();
INSERT INTO SEQ100 VALUES(),();

SELECT X FROM SEQ100 LIMIT 52;

##EXTRACTING DISTINCT ID OR WEEK_NUMBER WHICH ARE PRESENT IN SEQ100 BUT NOT IN CLEAN_WEEKLY_SALES
SELECT DISTINCT X FROM SEQ100 WHERE X NOT IN(SELECT distinct WEEK_NUMBER FROM CLEAN_WEEKLY_SALES);

##TOTAL TRANSACTIONS BASED ON YEARS
SELECT YEAR_NUMBER, SUM(TRANSACTIONS) AS TOTAL_TRANSACTIONS
FROM CLEAN_WEEKLY_SALES
GROUP BY YEAR_NUMBER;

##TOTAL SALES FOR EACH REGION FOR EACH MONTH
SELECT REGION,MONTH_NUMBER, SUM(SALES)AS TOTAL_SALES
FROM CLEAN_WEEKLY_SALES
GROUP BY MONTH_NUMBER,REGION;

##TOTAL SUM OF TRANSACTIONS FOR EACH PLATFORM
SELECT PLATFORM,SUM(TRANSACTIONS) FROM CLEAN_WEEKLY_SALES
GROUP BY PLATFORM;

##PERCENTAGE OF SALES FOR RETAIL AND FOR SHOPIFY

WITH CTE_MONTHLY_SALES AS
(SELECT MONTH_NUMBER,YEAR_NUMBER,PLATFORM,
SUM(SALES) AS MONTHLY_SALES
FROM CLEAN_WEEKLY_SALES
GROUP BY  MONTH_NUMBER,YEAR_NUMBER,PLATFORM)

SELECT MONTH_NUMBER,YEAR_NUMBER,
ROUND(100*MAX(CASE WHEN PLATFORM = 'RETAIL'
THEN MONTHLY_SALES ELSE NULL END)/SUM(MONTHLY_SALES),2) AS RETAIL_PERCENTAGE,
ROUND(100*MAX(CASE WHEN PLATFORM = 'SHOPIFY'
THEN MONTHLY_SALES ELSE NULL END)/SUM(MONTHLY_SALES),2) AS SHOPIFY_PERCENTAGE
FROM CTE_MONTHLY_SALES
GROUP BY MONTH_NUMBER,YEAR_NUMBER;

##PERCENTAGE OF SALES FOR DEMOGRAPHIC FOR EACH YEAR

SELECT YEAR_NUMBER,DEMOGRAPHIC,
SUM(SALES) AS YEARLY_SALES,
ROUND(100*SUM(SALES)/SUM(SUM(SALES))
OVER(PARTITION BY  DEMOGRAPHIC),2) AS PERCENTAGE
FROM CLEAN_WEEKLY_SALES
GROUP BY YEAR_NUMBER,DEMOGRAPHIC;

##AGE_BAND AND DEMOGRAPHIC VALUES CONTRIBUTE THE MOST TO RETAIL SALES

SELECT AGE_BAND,DEMOGRAPHIC,
SUM(SALES) AS TOTAL_SALES
FROM CLEAN_WEEKLY_SALES
WHERE PLATFORM = 'RETAIL'
GROUP BY AGE_BAND,DEMOGRAPHIC
ORDER BY TOTAL_SALES DESC;


